### ISSUE TITLE
optimizer无法加载

### ISSUE THREAD

**Issue by hddsama12** [FeiyuZhang98/IncreLoRA#1]
由于训练过程中optimizer的参数组增加了，optimizer的checkpoint无法正确加载怎么办？

**Comment by FeiyuZhang98** [comment]
你好，我们没有添加模型和optimizer的本地加载代码，直接加载保存在本地的权重可能会造成错误。如果你想要重新加载并继续训练，需要在一开始根据保存的内容初始化model和optimizer，并加载本地权重，传入到Trainer。后续我们会补充这部分的代码。
