### ISSUE TITLE
Random seeds information

### ISSUE THREAD

**Issue by SEONHOK** [FeiyuZhang98/IncreLoRA#2]
Hi! I want to reproduce the results. Could I know the random seed numbers that you chose for the results? Thanks!

**Comment by FeiyuZhang98** [comment]
Hi, we used the following random seed numbers: seeds = (41,42,43,44,45). These seeds should help you to precisely replicate the experiments and achieve the same results as we did.
Please don't hesitate to contact us if you have further questions or need more assistance!

**Comment by SEONHOK** [comment]
Thanks!
